name: ${project.artifactId}
main: com.mcme.themed.ThemedBuilds
version: ${project.version}
website: ${project.url}
description: ThemedBuild plugin
author: meggawatts
permissions:
  themed.admin.create:
    default: op
  themed.admin.break:
    default: op
commands:
   tb:
      description: Themed Build command
      usage: |
             /<command> create [name]
             /<command> settopic [topicid]