name: ${project.artifactId}
main: co.mcme.themedbuilds.ThemedBuildPlugin
version: ${project.version}
website: ${project.url}
authors: [meggawatts]
author: meggawatts
depend: [WorldEdit]
commands:
    turtle:
        description: Creates an ASCII turtle in chat.
        usage: /turtle   
