name: ${project.artifactId}
main: co.mcme.themed.ThemedBuilds
version: ${project.version}
website: ${project.url}
description: ${project.description}
author: meggawatts
commands:
   tb:
      description: Themed Build command
      usage: |
             /<command>