general:
  debug: false
sql:
  host: localhost
  port: 3306
  user: root
  password: 
  database: minecraft
  tbtable: tb_builds
  playertable: tb_players
  logdelay: 2
builds:
  current:
    name: default
    main:
      a1:
        ==: Vector
        x: -3.0
        y: 5.0
        z: 176.0
      b1:
        ==: Vector
        x: -3.0
        y: 5.0
        z: 182.0
    supplement:
      a1:
        ==: Vector
        x: -3.0
        y: 5.0
        z: 176.0
      b1:
        ==: Vector
        x: -3.0
        y: 5.0
        z: 182.0
